### ISSUE TITLE
Tutorial displays all comments for each post

### ISSUE THREAD

**Issue by delueg** [Greg0/Lazer-Database#34]
Hello,

i wanted to get into Relations and how everything works.

But when i set up the tutorial no more no less. Each post has all comments displayed.
Also email and username are not displayed.

<img width="1028" alt="screen shot 2018-06-14 at 23 24 31" src="https://user-images.githubusercontent.com/2786530/41439191-1f6de590-702a-11e8-87e7-c4e16268fada.png">

**Comment by anant-svc** [comment]
Hi, I understood your issue & believe me I will come up with fixing relation issue & examples asap.

**Comment by Greg0** [comment]
yep, It is necessary to rethink proceeding query and behaviour of object (it state changes).

**Comment by anant-svc** [comment]
I've tested & fixed relations `tutorial.md` file & added new use cases also. Please verify if it works you expected.

**Comment by Greg0** [comment]
I'm sory but you didn't fixed anything. Just changed tutorial, which was good. Just code works wrong.

**Comment by Ananth747** [comment]
At first I though there were some issues in code. Then I used `tutorial` and php show`d up errors while calling comments `fetchAll` in foreach loop. While trying I got the way to use functions - fetch, limit, where.

Here I have to use `limit`, `where` before `comments` `foreach` loop otherwise I can't get user data.

**Comment by anant-svc** [comment]
At first I though there were some issues in code. Then I used `tutorial` and php show`d up errors while calling comments `fetchAll` in foreach loop. While trying I got the way to use functions - fetch, limit, where.

Here I have to use `limit`, `where` before `comments` `foreach` loop otherwise I can't get user data.
